version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10  
    
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install

      # Upgrade AWS CLI to the last version
      - pip install --upgrade awscli